require_relative 'models/character'
require_relative 'models/strike'
require_relative 'models/attributes'
require_relative 'models/fight'
require_relative 'models/castle'
require_relative 'models/exit'
